// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_reset.sql

package database

import (
	"context"
)

const adminReset = `-- name: AdminReset :exec
DELETE FROM users
`

func (q *Queries) AdminReset(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, adminReset)
	return err
}
