// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: set_chirpy_red.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const setChirpyRed = `-- name: SetChirpyRed :exec
UPDATE users
SET is_chirpy_red = $1
WHERE ID = $2
`

type SetChirpyRedParams struct {
	IsChirpyRed bool
	ID          uuid.UUID
}

func (q *Queries) SetChirpyRed(ctx context.Context, arg SetChirpyRedParams) error {
	_, err := q.db.ExecContext(ctx, setChirpyRed, arg.IsChirpyRed, arg.ID)
	return err
}
