// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_refresh_token.sql

package database

import (
	"context"
	"database/sql"
)

const updateRefreshToken = `-- name: UpdateRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = $1,
	updated_at = NOW()
WHERE token = $2
`

type UpdateRefreshTokenParams struct {
	RevokedAt sql.NullTime
	Token     string
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshToken, arg.RevokedAt, arg.Token)
	return err
}
